#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM php:7.2-fpm
LABEL maintainer="chinayin <whereismoney@qq.com>" Version="7.2"
ENV DEBIAN_FRONTEND=noninteractive FPM_IMAGE_VERSION="2020-08-14 14:48"

ARG CHANGE_SOURCE=true
ARG TIMEZONE=Asia/Shanghai
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    sed -i 's/deb.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list && \
    sed -i 's/security-cdn.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list \
;fi && cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo "${TIMEZONE}" > /etc/timezone;

RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
        libz-dev libmemcached-dev libssl-dev libmcrypt-dev \
        libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev \
        libonig-dev libyaml-dev \
        curl; \
    pecl channel-update pecl.php.net; \
    # Docker ext install
    docker-php-ext-install pdo_mysql; \
    docker-php-ext-install fileinfo exif; \
    docker-php-ext-configure gd --prefix=/usr --with-gd --with-webp-dir --with-jpeg-dir --with-png-dir --with-zlib-dir --with-freetype-dir; \
    docker-php-ext-install gd; \
    # Pecl install
    pecl install uuid && docker-php-ext-enable uuid; \
    pecl install yaml && docker-php-ext-enable yaml; \
    pecl install -o -f redis && docker-php-ext-enable redis; \
    pecl install mongodb && docker-php-ext-enable mongodb; \
    pecl install memcached && docker-php-ext-enable memcached; \
    # Clean up
    pecl clear-cache && apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && rm /var/log/lastlog /var/log/faillog; \
    # Check PHP version
    php -v | head -n 1 | grep -q "PHP ${PHP_VERSION}";

# Configure non-root user.
ARG PUID=1000
ARG PGID=1000
ENV PUID=${PUID} PGID=${PGID}
RUN groupmod -o -g ${PGID} www-data && usermod -o -u ${PUID} -g www-data www-data
