name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 7.2, 7.4 ]
        os: [ buster ]
        variant: [ fpm, cli ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
          --pull \
          --file Dockerfile \
          --tag chinayin/php:${{ matrix.major }}-${{ matrix.variant }} \
          --tag chinayin/php:${{ matrix.major }}-${{ matrix.variant }}-${{ matrix.os }} \
          --tag chinayin/php:$(grep -oE 'PHP_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')-${{ matrix.variant }} \
          .
      - name: Push image to Docker hub
        if: success()
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push chinayin/php:${{ matrix.major }}-${{ matrix.variant }}
          docker push chinayin/php:${{ matrix.major }}-${{ matrix.variant }}-${{ matrix.os }}
          docker push chinayin/php:$(grep -oE 'PHP_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')-${{ matrix.variant }}
          docker logout

  build-slim:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        major: [ 7.2, 7.4 ]
        os: [ slim ]
        variant: [ fpm, cli ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
          --pull \
          --file Dockerfile \
          --tag chinayin/php:${{ matrix.major }}-${{ matrix.variant }}-${{ matrix.os }} \
          --tag chinayin/php:$(grep -oE 'PHP_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')-${{ matrix.variant }}-${{ matrix.os }} \
          .
      - name: Push image to Docker hub
        if: success()
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push chinayin/php:${{ matrix.major }}-${{ matrix.variant }}-${{ matrix.os }}
          docker push chinayin/php:$(grep -oE 'PHP_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')-${{ matrix.variant }}-${{ matrix.os }}
          docker logout
