name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 7.2, 7.4 ]
        os: [ buster ]
        variant: [ fpm, cli ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep -oE 'PHP_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
          pull: true
          push: true
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.variant }}
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.variant }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.variant }}
  build-slim:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        major: [ 7.2, 7.4 ]
        os: [ slim ]
        variant: [ fpm, cli ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep -oE 'PHP_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
          pull: true
          push: true
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.variant }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.variant }}-${{ matrix.os }}
